# Generated by Django 5.0.1 on 2024-01-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='category',
            new_name='genre',
        ),
    ]
