# Generated by Django 5.0.1 on 2024-01-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_categories_genre_rename_category_movies_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashTags',
            new_name='HashTag',
        ),
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
