# Generated by Django 4.2.3 on 2024-01-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movie_genre_alter_movie_hashtag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Trailer_url',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='movie',
            name='hashtag',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='movie',
            name='source',
            field=models.CharField(default='Nkiri', max_length=250),
        ),
    ]
